function deepFreeze(value) {
  if (!value || typeof value !== "object" || Object.isFrozen(value)) return value;
  for (const nested of Object.values(value)) deepFreeze(nested);
  return Object.freeze(value);
}

export const CONTENT_VERSION = "creature-pet-v2-2026-07-15";

export const SLOTS = deepFreeze([
  {
    id: "presence",
    options: [
      {
        id: "hide",
        effect: "hide",
        motionMs: 2200,
        holdMs: 1800,
        reaction: "嘘，它把在线状态折起来盖住了脸。",
        organId: "offline-camo",
        organName: "假装掉线纸",
        nameAlias: "掉线",
        axes: { approach: -1, output: -1, tempo: -1 },
        evidence: "它用假装掉线纸完成了当场消失。",
      },
      {
        id: "reply",
        effect: "reply",
        motionMs: 780,
        holdMs: 1800,
        reaction: "事情还没出现，问号已经发射。",
        organId: "instant-reply-rig",
        organName: "秒回天线",
        nameAlias: "秒回",
        axes: { approach: 1, output: 1, tempo: 1 },
        evidence: "它的秒回天线总比下文先到场。",
      },
    ],
  },
  {
    id: "energy",
    options: [
      {
        id: "plug-umbilical",
        effect: "plug-umbilical",
        motionMs: 840,
        holdMs: 1800,
        reaction: "它把充电线长成脐带，开始向墙认亲。",
        organId: "plug-umbilical",
        organName: "插头脐带",
        nameAlias: "插头",
        axes: { approach: 1, output: -1, tempo: -1 },
        evidence: "它用插头脐带完成了紧急投靠。",
      },
      {
        id: "battery-sac",
        effect: "battery-sac",
        motionMs: 760,
        holdMs: 1800,
        reaction: "它鼓起省电背囊，只保留了焦虑功能。",
        organId: "battery-sac",
        organName: "省电背囊",
        nameAlias: "省电",
        axes: { approach: -1, output: 1, tempo: 1 },
        evidence: "它把屏幕和尊严一起调暗。",
      },
    ],
  },
  {
    id: "interruption",
    options: [
      {
        id: "keyboard-hands",
        effect: "keyboard-hands",
        motionMs: 880,
        holdMs: 1800,
        reaction: "它长出键盘手，顺手接管了你今晚。",
        organId: "keyboard-hands",
        organName: "键盘手",
        nameAlias: "键盘",
        axes: { approach: 1, output: -1, tempo: -1 },
        evidence: "它用键盘手把小事敲成了夜班。",
      },
      {
        id: "receipt-tongue",
        effect: "receipt-tongue",
        motionMs: 800,
        holdMs: 1800,
        reaction: "它弹出收到舌，脑子仍在加载。",
        organId: "receipt-tongue",
        organName: "收到舌",
        nameAlias: "收到",
        axes: { approach: -1, output: 1, tempo: 1 },
        evidence: "任务刚出现，收到舌已经提前交付。",
      },
    ],
  },
  {
    id: "deadline",
    options: [
      {
        id: "countdown-horns",
        effect: "countdown-horns",
        motionMs: 860,
        holdMs: 1800,
        reaction: "时间越少，它的角越精神。",
        organId: "countdown-horns",
        organName: "倒计时角",
        nameAlias: "倒数",
        axes: { approach: 1, output: -1, tempo: 1 },
        evidence: "它用倒计时角把十分钟顶成了一小时。",
      },
      {
        id: "final-final-tail",
        effect: "final-final-tail",
        motionMs: 820,
        holdMs: 1800,
        reaction: "尾巴刚长出来，已经叫 final_7。",
        organId: "final-final-tail",
        organName: "终稿尾",
        nameAlias: "终稿",
        axes: { approach: -1, output: 1, tempo: -1 },
        evidence: "内容还没开始，空白文件先接上终稿尾。",
      },
    ],
  },
  {
    id: "arrival",
    options: [
      {
        id: "elevator-legs",
        effect: "elevator-legs",
        motionMs: 860,
        holdMs: 1800,
        reaction: "它提前在楼下等那个“马上”。",
        organId: "elevator-legs",
        organName: "电梯腿",
        nameAlias: "电梯",
        axes: { approach: 1, output: -1, tempo: 1 },
        evidence: "它用电梯腿换来了十分钟站立。",
      },
      {
        id: "sofa-suction",
        effect: "sofa-suction",
        motionMs: 820,
        holdMs: 1800,
        reaction: "沙发吸盘已经签收了它本人。",
        organId: "sofa-suction",
        organName: "沙发吸盘",
        nameAlias: "沙发",
        axes: { approach: -1, output: 1, tempo: -1 },
        evidence: "它用沙发吸盘完成了永久续躺。",
      },
    ],
  },
  {
    id: "feed",
    options: [
      {
        id: "hotspot-gills",
        effect: "hotspot-gills",
        motionMs: 900,
        holdMs: 1800,
        reaction: "它开始在消息洪水里换气。",
        organId: "hotspot-gills",
        organName: "热点鳃",
        nameAlias: "热点",
        axes: { approach: 1, output: -1, tempo: -1 },
        evidence: "它用热点鳃逐条吸入，至今没有浮上来。",
      },
      {
        id: "summary-beak",
        effect: "summary-beak",
        motionMs: 760,
        holdMs: 1800,
        reaction: "正文还没看，摘要喙已经叼走结论。",
        organId: "summary-beak",
        organName: "摘要喙",
        nameAlias: "摘要",
        axes: { approach: -1, output: 1, tempo: 1 },
        evidence: "它只用摘要喙取走了最后一句。",
      },
    ],
  },
  {
    id: "shutdown",
    options: [
      {
        id: "infinite-scroll-eye",
        effect: "infinite-scroll-eye",
        motionMs: 900,
        holdMs: 1800,
        reaction: "它多长一只眼，专门寻找最后一条。",
        organId: "infinite-scroll-eye",
        organName: "无限下划眼",
        nameAlias: "下划",
        axes: { approach: 1, output: 1, tempo: -1 },
        evidence: "它发现了下一条最后一条。",
      },
      {
        id: "pillow-brain",
        effect: "pillow-brain",
        motionMs: 740,
        holdMs: 1800,
        reaction: "半个脑子折成枕头，剩下一半还在刷。",
        organId: "pillow-brain",
        organName: "枕头脑",
        nameAlias: "枕头",
        axes: { approach: -1, output: -1, tempo: 1 },
        evidence: "手机扣下了，枕头脑还在梦里更新。",
      },
    ],
  },
]);

export const QUESTION_VARIANTS = deepFreeze([
  {
    id: "presence-common",
    slotId: "presence",
    kind: "common",
    scene: "group-chat",
    prompt: "群里突然有人发「在吗」，你会？",
    options: [
      { id: "hide", label: "先装死", note: "等它自己长出下文" },
      { id: "reply", label: "立刻回", note: "先把「咋了」发射出去" },
    ],
  },
  {
    id: "presence-work",
    slotId: "presence",
    kind: "work",
    scene: "work-mention",
    prompt: "工作群只 @ 你，没说干嘛，你会？",
    options: [
      { id: "hide", label: "等他补充", note: "先让需求学会说完整话" },
      { id: "reply", label: "先回「我在」", note: "人先到，需求随后补票" },
    ],
  },
  {
    id: "presence-study",
    slotId: "presence",
    kind: "study",
    scene: "study-group",
    prompt: "小组群弹来「在吗」，你会？",
    options: [
      { id: "hide", label: "等题目出现", note: "问号没有作业，不予受理" },
      { id: "reply", label: "先回「怎么了」", note: "先把自己发进任务里" },
    ],
  },
  {
    id: "presence-social-hot",
    slotId: "presence",
    kind: "social-hot",
    scene: "social-comfort",
    prompt: "群里突然问「谁来哄一下我」，你会？",
    options: [
      { id: "hide", label: "让空气先上", note: "沉默正在组织安慰" },
      { id: "reply", label: "我来回一句", note: "疗效不保证，响应很及时" },
    ],
  },
  {
    id: "energy-common",
    slotId: "energy",
    kind: "common",
    scene: "low-battery-map",
    prompt: "手机电量只剩 1%，地图还开着，你会？",
    options: [
      { id: "plug-umbilical", label: "找插座续命", note: "人可以断网，手机不能断气" },
      { id: "battery-sac", label: "把亮度调没", note: "屏幕暗了，焦虑还亮着" },
    ],
  },
  {
    id: "energy-work",
    slotId: "energy",
    kind: "work",
    scene: "laptop-battery",
    prompt: "开会前电脑只剩 8%，你会？",
    options: [
      { id: "plug-umbilical", label: "抱线找墙", note: "会议可以断，电脑不行" },
      { id: "battery-sac", label: "一键省电", note: "先把屏幕和存在感调低" },
    ],
  },
  {
    id: "energy-study",
    slotId: "energy",
    kind: "study",
    scene: "tablet-battery",
    prompt: "上课前平板只剩 3%，你会？",
    options: [
      { id: "plug-umbilical", label: "钻桌找电", note: "知识没进，插头先进去" },
      { id: "battery-sac", label: "省电听天书", note: "只保留老师和焦虑" },
    ],
  },
  {
    id: "energy-social-hot",
    slotId: "energy",
    kind: "social-hot",
    scene: "anxiety-battery",
    prompt: "电量见底，焦虑满格，你会？",
    options: [
      { id: "plug-umbilical", label: "外接续命", note: "墙上就是临时监护室" },
      { id: "battery-sac", label: "只留焦虑", note: "其他功能一律暂停" },
    ],
  },
  {
    id: "interruption-common",
    slotId: "interruption",
    kind: "common",
    scene: "small-favor",
    prompt: "有人发来一句「顺手帮我弄一下」，你会？",
    options: [
      { id: "keyboard-hands", label: "现在就弄", note: "顺手，一般是对方看着顺手" },
      { id: "receipt-tongue", label: "先回收到", note: "嘴已交付，大脑仍在排期" },
    ],
  },
  {
    id: "interruption-work",
    slotId: "interruption",
    kind: "work",
    scene: "late-revision",
    prompt: "17:40 来句「简单改一下」，你会？",
    options: [
      { id: "keyboard-hands", label: "现在开改", note: "简单，一般是对方看着简单" },
      { id: "receipt-tongue", label: "先回收到", note: "嘴已交付，大脑仍在排期" },
    ],
  },
  {
    id: "interruption-study",
    slotId: "interruption",
    kind: "study",
    scene: "group-integration",
    prompt: "组员说「你顺手整合」，你会？",
    options: [
      { id: "keyboard-hands", label: "打开文档", note: "组员已隐身，光标没有" },
      { id: "receipt-tongue", label: "先回收到", note: "收到不代表我收得动" },
    ],
  },
  {
    id: "interruption-social-hot",
    slotId: "interruption",
    kind: "social-hot",
    scene: "another-version",
    prompt: "AI 刚给三版，又要顺手来一版，你会？",
    options: [
      { id: "keyboard-hands", label: "继续敲", note: "AI 负责三版，我负责第四次崩溃" },
      { id: "receipt-tongue", label: "先回没问题", note: "问题很多，回复没有" },
    ],
  },
  {
    id: "deadline-common",
    slotId: "deadline",
    kind: "common",
    scene: "blank-deadline",
    prompt: "明早要交的表，现在还没开头，你会？",
    options: [
      { id: "countdown-horns", label: "先冲一版", note: "先让空白失去清白" },
      { id: "final-final-tail", label: "先改名 final", note: "内容可以晚，终稿必须早" },
    ],
  },
  {
    id: "deadline-work",
    slotId: "deadline",
    kind: "work",
    scene: "end-of-day-deadline",
    prompt: "17:58 问「今晚能给吗」，你会？",
    options: [
      { id: "countdown-horns", label: "先冲一版", note: "先让空白失去清白" },
      { id: "final-final-tail", label: "先建终稿", note: "内容可以晚，终稿必须早" },
    ],
  },
  {
    id: "deadline-study",
    slotId: "deadline",
    kind: "study",
    scene: "homework-deadline",
    prompt: "23:40 才发现作业今晚截止，你会？",
    options: [
      { id: "countdown-horns", label: "先写开头", note: "有开头就算项目启动" },
      { id: "final-final-tail", label: "先建 final", note: "先让文件名顺利毕业" },
    ],
  },
  {
    id: "deadline-social-hot",
    slotId: "deadline",
    kind: "social-hot",
    scene: "problem-not-big",
    prompt: "嘴上问题不大，倒计时已经很大，你会？",
    options: [
      { id: "countdown-horns", label: "先冲", note: "嘴上不大，手速要大" },
      { id: "final-final-tail", label: "先让文件毕业", note: "内容留级，文件名先毕业" },
    ],
  },
  {
    id: "arrival-common",
    slotId: "arrival",
    kind: "common",
    scene: "delivery-downstairs",
    prompt: "外卖显示「骑手即将到达」，你会？",
    options: [
      { id: "elevator-legs", label: "现在下楼", note: "人先到，外卖慢慢到" },
      { id: "sofa-suction", label: "再躺亿会儿", note: "亿会儿是沙发的计量单位" },
    ],
  },
  {
    id: "arrival-work",
    slotId: "arrival",
    kind: "work",
    scene: "office-delivery",
    prompt: "同城急送显示「即将到公司」，你会？",
    options: [
      { id: "elevator-legs", label: "现在下楼", note: "人先到，急送慢慢到" },
      { id: "sofa-suction", label: "再坐一分钟", note: "再坐一分钟也是时间管理" },
    ],
  },
  {
    id: "arrival-study",
    slotId: "arrival",
    kind: "study",
    scene: "dorm-delivery",
    prompt: "快递显示「即将到宿舍楼下」，你会？",
    options: [
      { id: "elevator-legs", label: "穿拖鞋冲", note: "拖鞋先冲，灵魂随后" },
      { id: "sofa-suction", label: "再躺亿会儿", note: "亿会儿是宿舍的计量单位" },
    ],
  },
  {
    id: "arrival-social-hot",
    slotId: "arrival",
    kind: "social-hot",
    scene: "spinning-location",
    prompt: "定位还在转圈，对方说「马上到」，你会？",
    options: [
      { id: "elevator-legs", label: "先下楼", note: "先替定位到场" },
      { id: "sofa-suction", label: "相信定位", note: "相信科技，也相信床" },
    ],
  },
  {
    id: "feed-common",
    slotId: "feed",
    kind: "common",
    scene: "group-99-plus",
    prompt: "群聊突然变成 99+，你会？",
    options: [
      { id: "hotspot-gills", label: "从头补课", note: "试图找出事情从哪开始坏的" },
      { id: "summary-beak", label: "直接问结论", note: "过程可以淹，结论必须浮着" },
    ],
  },
  {
    id: "feed-work",
    slotId: "feed",
    kind: "work",
    scene: "long-proposal",
    prompt: "群里扔来 18 页方案，你会？",
    options: [
      { id: "hotspot-gills", label: "全部看完", note: "从封面开始接受洗礼" },
      { id: "summary-beak", label: "先找一句结论", note: "十八页里总有一句人话" },
    ],
  },
  {
    id: "feed-study",
    slotId: "feed",
    kind: "study",
    scene: "long-slides",
    prompt: "42 页课件明早要测，你会？",
    options: [
      { id: "hotspot-gills", label: "逐页补", note: "不放过任何一页天书" },
      { id: "summary-beak", label: "先问考哪", note: "知识太多，先抓考点" },
    ],
  },
  {
    id: "feed-social-hot",
    slotId: "feed",
    kind: "social-hot",
    scene: "one-more-episode",
    prompt: "最后一条还有下集，你会？",
    options: [
      { id: "hotspot-gills", label: "接着看", note: "下集也是最后一条" },
      { id: "summary-beak", label: "叼走一句总结", note: "内容可以沉，结论必须浮着" },
    ],
  },
  {
    id: "shutdown-common",
    slotId: "shutdown",
    kind: "common",
    scene: "midnight-feed",
    prompt: "凌晨两点，你还在往下刷——",
    options: [
      { id: "infinite-scroll-eye", label: "再刷亿条", note: "最后亿条，看完就睡" },
      { id: "pillow-brain", label: "把手机扣下", note: "手机睡了，脑子还在刷" },
    ],
  },
  {
    id: "shutdown-work",
    slotId: "shutdown",
    kind: "work",
    scene: "after-work-red-dot",
    prompt: "下班后群里又亮红点，你会？",
    options: [
      { id: "infinite-scroll-eye", label: "点开看看", note: "红点亮了，理智暗了" },
      { id: "pillow-brain", label: "把手机扣下", note: "手机下班，脑子留守" },
    ],
  },
  {
    id: "shutdown-study",
    slotId: "shutdown",
    kind: "study",
    scene: "one-more-solution",
    prompt: "说好只刷一页题解，已经一点半，你会？",
    options: [
      { id: "infinite-scroll-eye", label: "再看一道", note: "下一道也是最后一道" },
      { id: "pillow-brain", label: "强制关机", note: "关机比自律快一步" },
    ],
  },
  {
    id: "shutdown-social-hot",
    slotId: "shutdown",
    kind: "social-hot",
    scene: "finger-reconsiders",
    prompt: "手机说晚安，手指说再议，你会？",
    options: [
      { id: "infinite-scroll-eye", label: "再议一条", note: "最后一条正在批量生产" },
      { id: "pillow-brain", label: "当场关机", note: "手指下班，推荐流留守" },
    ],
  },
]);

const variantsById = new Map(QUESTION_VARIANTS.map((variant) => [variant.id, variant]));

function buildQuestion(packId, variantKind, slot) {
  const variant = variantsById.get(`${slot.id}-${variantKind}`);
  return {
    id: slot.id,
    slotId: slot.id,
    packId,
    variantId: variant.id,
    variantKind,
    scene: variant.scene,
    prompt: variant.prompt,
    options: slot.options.map((outcome, index) => ({
      ...outcome,
      ...variant.options[index],
    })),
  };
}

function buildPack(id, label, variantKind) {
  return {
    id,
    label,
    variantKind,
    questions: SLOTS.map((slot) => buildQuestion(id, variantKind, slot)),
  };
}

export const PACKS = deepFreeze({
  work: buildPack("work", "工位续命", "work"),
  study: buildPack("study", "课表追杀", "study"),
  general: buildPack("general", "随便活着", "common"),
});

// The current reducer/controller still owns the accepted five-turn V1 flow.
// Keep this literal snapshot byte-for-byte compatible until those layers migrate to PACKS.
export const QUESTIONS = deepFreeze([
  {
    id: "presence",
    scene: "group-chat",
    prompt: "群里突然有人发「在吗」，你会？",
    options: [
      {
        id: "hide",
        label: "先装死",
        note: "已读空气，保持失联",
        effect: "hide",
        motionMs: 2200,
        holdMs: 650,
        reaction: "它学会了假装掉线。",
        organId: "offline-camo",
        organName: "假装掉线纸",
        axes: { approach: -1, output: -1 },
        evidence: "遇到「在吗」时，它用假装掉线纸盖住了脸。",
      },
      {
        id: "reply",
        label: "立刻回",
        note: "先把“咋了”发射出去",
        effect: "reply",
        motionMs: 780,
        holdMs: 650,
        reaction: "它进化出了秒回器官。",
        organId: "instant-reply-rig",
        organName: "秒回天线",
        axes: { approach: 1, output: 1 },
        evidence: "遇到「在吗」时，它抢先长出了秒回天线。",
      },
    ],
  },
  {
    id: "battery",
    scene: "low-battery",
    prompt: "手机只剩 1% 电，你会？",
    options: [
      {
        id: "plug-umbilical",
        label: "找插座续命",
        note: "人可以断网，手机不能断气",
        effect: "plug-umbilical",
        motionMs: 840,
        holdMs: 650,
        reaction: "它把充电线长成了脐带，开始反向给插座充电。",
        organId: "plug-umbilical",
        organName: "插头脐带",
        axes: { approach: 1, output: -1 },
        evidence: "只剩 1% 电时，它把插头接成了插头脐带。",
      },
      {
        id: "battery-sac",
        label: "开省电模式",
        note: "把亮度和尊严一起调低",
        effect: "battery-sac",
        motionMs: 760,
        holdMs: 650,
        reaction: "它进入省电模式，只保留了焦虑功能。",
        organId: "battery-sac",
        organName: "省电背囊",
        axes: { approach: -1, output: 1 },
        evidence: "只剩 1% 电时，它鼓起了只供焦虑用的省电背囊。",
      },
    ],
  },
  {
    id: "revision",
    scene: "work-chat",
    prompt: "老板说「简单改一下」，你会？",
    options: [
      {
        id: "keyboard-hands",
        label: "现在就改",
        note: "简单，一般是对方看起来简单",
        effect: "keyboard-hands",
        motionMs: 880,
        holdMs: 650,
        reaction: "它长出了键盘手，开始替你制造新需求。",
        organId: "keyboard-hands",
        organName: "键盘手",
        axes: { approach: 1, output: -1 },
        evidence: "听见「简单改一下」，它用键盘手接管了加班。",
      },
      {
        id: "receipt-tongue",
        label: "先回收到",
        note: "嘴已交付，大脑仍在排期",
        effect: "receipt-tongue",
        motionMs: 800,
        holdMs: 650,
        reaction: "它长出了一条“收到”舌，但大脑没有收到。",
        organId: "receipt-tongue",
        organName: "收到舌",
        axes: { approach: -1, output: 1 },
        evidence: "听见「简单改一下」，它弹出了比脑子快的收到舌。",
      },
    ],
  },
  {
    id: "delivery",
    scene: "delivery-tracker",
    prompt: "外卖显示「骑手即将到达」，你会？",
    options: [
      {
        id: "elevator-legs",
        label: "现在下楼",
        note: "用十分钟等待“即将”",
        effect: "elevator-legs",
        motionMs: 860,
        holdMs: 650,
        reaction: "它长出了电梯腿，下楼速度取决于信号。",
        organId: "elevator-legs",
        organName: "电梯腿",
        axes: { approach: 1, output: -1 },
        evidence: "骑手即将到达时，它装上了信号控制的电梯腿。",
      },
      {
        id: "sofa-suction",
        label: "再躺一分钟",
        note: "一分钟是沙发的计量单位",
        effect: "sofa-suction",
        motionMs: 820,
        holdMs: 650,
        reaction: "它进化出了沙发吸盘，外卖到了也拔不下来。",
        organId: "sofa-suction",
        organName: "沙发吸盘",
        axes: { approach: -1, output: 1 },
        evidence: "骑手即将到达时，它用沙发吸盘永久续躺。",
      },
    ],
  },
  {
    id: "doomscroll",
    scene: "midnight-feed",
    prompt: "凌晨两点还在往下刷，你会？",
    options: [
      {
        id: "infinite-scroll-eye",
        label: "再看一条",
        note: "最后一条，下边还有最后一条",
        effect: "infinite-scroll-eye",
        motionMs: 900,
        holdMs: 650,
        reaction: "它多长了一只无限下划眼，永远看不到底。",
        organId: "infinite-scroll-eye",
        organName: "无限下划眼",
        axes: { approach: 1, output: 1 },
        evidence: "凌晨两点，它用无限下划眼继续寻找最后一条。",
      },
      {
        id: "pillow-brain",
        label: "手机先睡",
        note: "本人稍后尝试关机",
        effect: "pillow-brain",
        motionMs: 740,
        holdMs: 650,
        reaction: "它把大脑的一半发育成了枕头。",
        organId: "pillow-brain",
        organName: "枕头脑",
        axes: { approach: -1, output: -1 },
        evidence: "凌晨两点，它把半个大脑折叠成了枕头脑。",
      },
    ],
  },
]);

export const ENDING_TEMPLATES = deepFreeze({
  "hide-consume-slow": {
    id: "hide-consume-slow",
    species: "缓存寄居蟹",
    form: "闷壳慢炖体",
    diagnosis: "你让它把所有事塞进壳里，再用缓冲圈慢慢咽。",
    observation: "外表没动，壳里已经缓存了八百种回复。",
    careWarning: "别连续敲壳，它会把你归进「稍后处理」。",
    shareLead: "没回，但全存了。",
    namePrefix: "慢存",
    nameSuffix: "壳蟹",
  },
  "hide-consume-fast": {
    id: "hide-consume-fast",
    species: "缓存寄居蟹",
    form: "秒封箱体",
    diagnosis: "它一见动静就秒封箱，撤退流程比消息先完成。",
    observation: "消息刚亮，壳门、遮脸纸和免打扰同时落下。",
    careWarning: "不要突然问「方便吗」，它会把房间也一起离线。",
    shareLead: "反应很快，主要快在消失。",
    namePrefix: "秒藏",
    nameSuffix: "箱蟹",
  },
  "hide-broadcast-slow": {
    id: "hide-broadcast-slow",
    species: "潜水喷墨鱿",
    form: "延迟冒泡体",
    diagnosis: "它本体潜水，想说的话会排队从墨囊里冒出来。",
    observation: "现场看不见它，半小时后能收到三条补充说明。",
    careWarning: "别催第二遍，旧回执还堵在喷水口。",
    shareLead: "不出现，只会延迟冒泡。",
    namePrefix: "迟泡",
    nameSuffix: "墨鱿",
  },
  "hide-broadcast-fast": {
    id: "hide-broadcast-fast",
    species: "潜水喷墨鱿",
    form: "秒喷回执体",
    diagnosis: "它躲得很快，回得更快，只有本人没到场。",
    observation: "身体已经下线，收到舌和秒回天线仍在值班。",
    careWarning: "别放进大群，它会替空气回复所有人。",
    shareLead: "没上线，回执已经喷满屏。",
    namePrefix: "秒喷",
    nameSuffix: "回执鱿",
  },
  "chase-consume-slow": {
    id: "chase-consume-slow",
    species: "热点吸尘兽",
    form: "细嚼全网体",
    diagnosis: "它什么都想追着吸，还坚持逐条嚼完。",
    observation: "肚子里常驻 99+，每个红点都保留完整上下文。",
    careWarning: "定期清缓存，否则它会开始阅读路由器说明书。",
    shareLead: "什么都吃，吃得还特别认真。",
    namePrefix: "细嚼",
    nameSuffix: "吞吞兽",
  },
  "chase-consume-fast": {
    id: "chase-consume-fast",
    species: "热点吸尘兽",
    form: "涡轮吞榜体",
    diagnosis: "红点一亮它就开涡轮，先吞了再问能不能吃。",
    observation: "热点、需求和最后一条会从同一个进气口消失。",
    careWarning: "喂食时收好通知栏，它会连系统更新一起吞。",
    shareLead: "哪里有新动静，哪里就少一块。",
    namePrefix: "涡吞",
    nameSuffix: "吸尘兽",
  },
  "chase-broadcast-slow": {
    id: "chase-broadcast-slow",
    species: "通知喇叭龙",
    form: "蓄力单声道",
    diagnosis: "它先把动静攒进胸腔，再挑安静时慢慢播。",
    observation: "平时像静音，开口后能播到下一顿饭。",
    careWarning: "睡前别问它还有没有补充。",
    shareLead: "安静只是前摇，开口能播到下一顿饭。",
    namePrefix: "蓄声",
    nameSuffix: "慢播龙",
  },
  "chase-broadcast-fast": {
    id: "chase-broadcast-fast",
    species: "通知喇叭龙",
    form: "即时环绕声",
    diagnosis: "事情还没发生，它已经完成预告、直播和复盘。",
    observation: "每根天线都在播不同版本，而且都说自己是最终版。",
    careWarning: "靠近免打扰前，请先给免打扰戴耳塞。",
    shareLead: "不是话多，只是全身都能发通知。",
    namePrefix: "爆响",
    nameSuffix: "环绕龙",
  },
});

export const RESULTS = deepFreeze({
  "hide-consume": {
    id: "hide-consume",
    species: "缓存寄居蟹",
    observation: "擅长把消息、情绪和充电线一起塞进壳里，直到系统自动清理。",
    careWarning: "不要连续敲它的壳。它会假装这是一次软件更新。",
    shareLead: "表面没有回复，体内已经缓存了八百句。",
  },
  "hide-broadcast": {
    id: "hide-broadcast",
    species: "潜水喷墨鱿",
    observation: "身体在潜水，器官却会替它向全世界发出“收到”。",
    careWarning: "禁止放进工作群。墨汁会自动生成已读回执。",
    shareLead: "本体下线了，动静还在持续更新。",
  },
  "chase-consume": {
    id: "chase-consume",
    species: "热点吸尘兽",
    observation: "看到红点就扑上去，把热搜、需求和最后一条全部吸进肚子。",
    careWarning: "请定期清理缓存，否则它会把路由器也当夜宵。",
    shareLead: "哪里有新鲜动静，哪里就有它的进食记录。",
  },
  "chase-broadcast": {
    id: "chase-broadcast",
    species: "通知喇叭龙",
    observation: "靠近任何事情都会长出新通知，安静时甚至会播报自己很安静。",
    careWarning: "睡前务必开启免打扰，它能用免打扰提醒吵醒你。",
    shareLead: "它不是爱回应，它只是无法停止向外冒泡。",
  },
});
