name: Deploy Static Sites

on:
  push:
    branches: [master]
    paths:
      - 'products/**'
  workflow_dispatch:
    inputs:
      force_deploy:
        description: Force deploy all products
        required: false
        default: 'false'

permissions:
  contents: read

jobs:
  deploy:
    uses: Time-Machine-Lab/TML_Github_Actions/.github/workflows/deploy-static-sites.yml@main
    with:
      force_deploy: ${{ github.event.inputs.force_deploy == 'true' }}
    secrets:
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_PASS: ${{ secrets.SERVER_PASS }}
